#!/bin/sh

/usr/bin/aegis-exec -s -u user dbus-send --dest=com.meego.msyncd --print-reply /synchronizer com.meego.msyncd.uninstallPlugin string:'nonameim'

# Clean up the feed items published by this application
/usr/bin/aegis-exec -s -u user dbus-send --dest=com.nokia.home.NonameIM --print-reply /eventfeed com.nokia.home.NonameIM.removeItemsBySourceName string:'SyncFW-event-nonameim'

# Make sure the uninstallation is always considered successful
exit 0
